### ISSUE TITLE
how to  fine tuning fuyu-8b

### ISSUE THREAD

**Issue by BlackHandsomeLee** [nengelmann/Fuyu-8B---Exploration#1]
i wana to  fine tuning fuyu-8b ,but do not  know the  complete code,
is there  any official document tell me how to do this？

**Comment by nengelmann** [comment]
@BlackHandsomeLee I'd recommend to contact or look for the official code from the authors.
Here's a link to their homepage: https://www.adept.ai/blog/fuyu-8b
